version: '3.5'
services:
  web: &web_base
    build: .
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - mysql
    tty: true
    stdin_open: true
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
  spring:
    <<: *web_base
    command: bundle exec spring server
    ports: []
    tty: false
    stdin_open: false
volumes:
  mysql_volume:
